### ISSUE TITLE
Panic when CheckRedirect is false

### ISSUE THREAD

**Issue by djsousuo** [SagerNet/cronet-go#10]
Run at Linux docker image `golang:1.18.3`

cmd/build/a.go

```
package main

import (
	"fmt"
	"github.com/sagernet/cronet-go"
	"net/http"
	"os"
	
)

func main() {
	client := &http.Client{
		Transport: &cronet.RoundTripper{
			CheckRedirect: func(newLocationUrl string) bool {
				return false
			},
		},
	}
	response, err := client.Get("https://httpbin.org/status/302")
	if err != nil {
		fmt.Println(err)
		os.Exit(2)
	}
	response.Write(os.Stderr)
	response.Body.Close()

}
```

Error stack after running: 
```HOSTNAME=80b5520f4a27
PWD=/code/cronet-go
HOME=/root
GOLANG_VERSION=1.18.3
TERM=xterm
SHLVL=1
PATH=/code/cronet-go/llvm/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GOPATH=/go
OLDPWD=/code
_=./main
CGO_LDFLAGS=-pie -I /code/cronet-go --sysroot=/code/cronet-go/sysroot -fuse-ld=lld -m64
CGO_CFLAGS=-I /code/cronet-go --sysroot=/code/cronet-go/sysroot -m64 -march=x86-64 -msse3
CC=clang
CGO_ENABLED=1
CGO_LDFLAGS_ALLOW=.*

root@80b5520f4a27:/code/cronet-go# 
root@80b5520f4a27:/code/cronet-go# ./a
SIGTRAP: trace trap
PC=0x7f8803aaff03 m=4 sigcode=128
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x561a7e02eae0, 0xc000099a68)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000099a40 sp=0xc000099a08 pc=0x561a7de0f67c
github.com/sagernet/cronet-go._Cfunc_Cronet_UrlRequest_Read(0x1270002382a0, 0x12700023e070)
	_cgo_gotypes.go:2553 +0x50 fp=0xc000099a68 sp=0xc000099a40 pc=0x561a7e025b70
github.com/sagernet/cronet-go.URLRequest.Read.func1({0xc000099ad0?}, {0xc000099ac8?})
	/code/cronet-go/url_request.go:73 +0x70 fp=0xc000099aa8 sp=0xc000099a68 pc=0x561a7e0297f0
github.com/sagernet/cronet-go.URLRequest.Read({0x0?}, {0xc0000d2000?})
	/code/cronet-go/url_request.go:73 +0x19 fp=0xc000099ac8 sp=0xc000099aa8 pc=0x561a7e029739
github.com/sagernet/cronet-go.(*urlResponse).Read(0xc0000cc000, {0xc0000d2000, 0x800, 0x2000})
	/code/cronet-go/transport.go:184 +0x128 fp=0xc000099b58 sp=0xc000099ac8 pc=0x561a7e0228e8
io.(*LimitedReader).Read(0xc00000e138, {0xc0000d2000?, 0x1d?, 0xc000099c50?})
	/usr/local/go/src/io/io.go:476 +0x45 fp=0xc000099b88 sp=0xc000099b58 pc=0x561a7de93f25
io.discard.ReadFrom({}, {0x561a7e097b08, 0xc00000e138})
	/usr/local/go/src/io/io.go:610 +0x72 fp=0xc000099be0 sp=0xc000099b88 pc=0x561a7de940f2
io.(*discard).ReadFrom(0x1a7e054780?, {0x561a7e097b08?, 0xc00000e138?})
	<autogenerated>:1 +0x37 fp=0xc000099c00 sp=0xc000099be0 pc=0x561a7de947d7
io.copyBuffer({0x561a7e0982a8, 0x561a7e234ce0}, {0x561a7e097b08, 0xc00000e138}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:412 +0x14b fp=0xc000099c80 sp=0xc000099c00 pc=0x561a7de93d0b
io.Copy(...)
	/usr/local/go/src/io/io.go:385
io.CopyN({0x561a7e0982a8, 0x561a7e234ce0}, {0x7f87da7ba878?, 0xc0000cc000}, 0x800)
	/usr/local/go/src/io/io.go:361 +0x9a fp=0xc000099cd0 sp=0xc000099c80 pc=0x561a7de93b3a
net/http.(*Client).do(0xc00006edb0, 0xc0000ca100)
	/usr/local/go/src/net/http/client.go:707 +0x81d fp=0xc000099ed0 sp=0xc000099cd0 pc=0x561a7dfe28fd
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:593
net/http.(*Client).Get(0xc0000021a0?, {0x561a7dd9c2be?, 0x561a7de12139?})
	/usr/local/go/src/net/http/client.go:480 +0x6a fp=0xc000099f28 sp=0xc000099ed0 pc=0x561a7dfe1e4a
main.main()
	/code/cronet-go/cmd/build/a.go:19 +0x85 fp=0xc000099f80 sp=0xc000099f28 pc=0x561a7e02b465
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x213 fp=0xc000099fe0 sp=0xc000099f80 pc=0x561a7de41dd3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000099fe8 sp=0xc000099fe0 pc=0x561a7de6dc01

rax    0xffffff2f
rbx    0x1270002382a0
rcx    0x0
rdx    0x1
rdi    0x1270002180c0
rsi    0xffffff2f
rbp    0x7f87db7f5d50
rsp    0x7f87db7f5d18
r8     0xc000032c00
r9     0x0
r10    0x8
r11    0x10
r12    0xc0000184a0
r13    0x0
r14    0x1270002382b0
r15    0x12700023e070
rip    0x7f8803aaff03
rflags 0x202
cs     0x33
fs     0x0
gs     0x0```

**Comment by djsousuo** [comment]
@nekohasekai  Please help to see this bug
